#!/bin/bash
find -name "* .js" -type f -delete
find -name "*.js" -type f -delete
#!/bin/bash
find -name "*.js" -type f -delete
find -name "*.js" -type f-delete
#!/bin/bash
find -name "*.js" -type f-delete
